apiVersion: v1
kind: Service
metadata:
  name: masterclass
spec:
  # NOTE Expose the service on each Node’s IP at a static port (the NodePort).
  # A ClusterIP service, to which the NodePort service will route, is
  # automatically created as well. You’ll be able to contact the NodePort
  # service from outside the cluster by requesting <NodeIP>:<NodePort>.
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    ravi-stack-component: app
    tier: frontend


#
# NOTE Exposes the service externally using a cloud provider’s load balancer.
# NodePort and ClusterIP services, to which the external load balancer will
# route, are automatically created.
# type: LoadBalancer
#
