apiVersion: v1
kind: Pod
metadata:
  name: busybox
  #namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      requests:
        cpu: 200m
        memory: 250Mi
      limits:
        cpu: 400m
        memory: 500Mi
  restartPolicy: Always
