# NOTE There are several ways to feed sensitive data into a k8s secret.
#
# (1) kubectl create secret generic db-secret \
#       --from-literal=username=myuser --from-literal=password=mypass
#
# (2) kubectl create secret generic db-secret \
#       --from-file=username.txt --from-file=password.txt
#
# (3) inside a file; DATA VALUES MUST BE BASE64 ENCODED
apiVersion: v1
kind: Secret
metadata:
  name: pg-user-pass
type: Opaque
data:
  username: ZmVycnVjY2luYXRvcg== # ferruccinator
  password: aWx1dkRvdHMh # iluvDots!
