apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  # NOTE The default service type is "ClusterIP". This exposes the service on a
  # cluster-internal IP. Choosing this makes the service only reachable from
  # within the cluster.
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    ravi-stack-component: postgres
    role: primary
    tier: backend
